# Generated by Django 6.1 on 2026-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram linki yoki username'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram linki yoki username'),
        ),
    ]
