# Generated by Django 6.1 on 2026-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_restaurant_instagram_restaurant_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Girgitdon', max_length=200, verbose_name='Platforma Nomi')),
                ('tagline', models.CharField(default='Kafe va Restoranlar uchun Raqamli QR Menyu Platformasi', max_length=255, verbose_name='Qisqa shior')),
                ('hero_title', models.CharField(default='Zamonaviy QR Menyu & Real-vaqt Oshxona Tizimi', max_length=255, verbose_name='Bosh sahifa asosiy sarlavha')),
                ('hero_description', models.TextField(default="Mijozlar telefonida qulay mobil menyuni ko'radi va darhol stoldan buyurtma beradi. Oshxona esa buyurtmani qabul qilib, tayyorlanish vaqtini belgilaydi — mijozda teskari sanoq ishlaydi!", verbose_name='Bosh sahifa matni')),
                ('contact_phone', models.CharField(blank=True, default='+998 90 000 00 00', max_length=50, null=True, verbose_name='Aloqa telefoni')),
                ('contact_telegram', models.CharField(blank=True, default='girgitdon_admin', max_length=100, null=True, verbose_name='Telegram admin')),
                ('announcement', models.TextField(blank=True, null=True, verbose_name="Bosh sahifadagi e'lon / yangilik")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
