# Generated by Django 6.1 on 2026-10-04 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('KITCHEN', 'Oshxona (Oshpaz)'), ('STAFF', 'Admin / Ofitsiant'), ('CUSTOMER', "Mijoz o'zi"), ('SYSTEM', 'Tizim')], max_length=20, null=True, verbose_name='Kim bekor qildi'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='GuestVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_uuid', models.CharField(db_index=True, max_length=64, verbose_name='Mehmon Unique ID')),
                ('table_number', models.IntegerField(blank=True, null=True, verbose_name="Oxirgi o'tirgan stoli")),
                ('device_name', models.CharField(default="Noma'lum Qurilma", max_length=150, verbose_name='Qurilma rusumi')),
                ('os_name', models.CharField(default="Noma'lum OS", max_length=100, verbose_name='Operatsion tizim')),
                ('browser_name', models.CharField(default="Noma'lum Brauzer", max_length=100, verbose_name='Brauzer')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Manzil')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faolmi (Buyurtma berganmi)')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Birinchi kirish vaqti')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik vaqti')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='menu.restaurant')),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('restaurant', 'guest_uuid')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='guest_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='menu.guestvisitor'),
        ),
    ]
