# Generated by Django 6.1 on 2026-10-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order_cancellation_reason_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestvisitor',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mijoz Ismi'),
        ),
        migrations.AddField(
            model_name='guestvisitor',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mijoz Telefoni'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='about_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name="Restoran Haqida (Tashqi ko'rinish) Banneri"),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Menyu tepasi Banner rasmi'),
        ),
    ]
