# Generated by Django 6.1 on 2026-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_guestvisitor_client_name_guestvisitor_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yetkazilgan vaqti'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name="To'langanmi"),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqti"),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Naqd pul'), ('CARD', 'Plastik karta (Humo/Uzcard)'), ('PAYME', 'Payme / Click / Online'), ('OTHER', 'Boshqa')], max_length=20, null=True, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('ACCEPTED', 'Qabul qilindi (Tayyorlanmoqda)'), ('READY', 'Tayyor'), ('DELIVERED', 'Yetkazildi (Kassada kutilmoqda)'), ('COMPLETED', "To'landi & Yakunlandi"), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=20),
        ),
    ]
